=== NineWorlds/xstreamer/bundles/us.nineworlds.xstreamer/resources/schemas/xws-spec.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "X-Wing Squadron Format Schema",
	"description": "A squadron for the X-Wing Miniatures Game in app-independent format for sharing, saving and moving between apps.",
	"type": "object",
	"required": 
	[
		"version",
		"faction",
		"pilots"
	],

	"additionalProperties": false,
	"properties": 
	{
		"version": 
		{
			"type": "string",
			"pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$",
			"description": "The version of the XWS spec used to create this data"
		},

		"name": 
		{
			"type": "string",
			"description": "The name of the squadron."
		},

		"points": 
		{
			"type": "integer",
			"description": "The total points spent creating this squadron."
		},

		"faction": 
		{
			"type": "string",
			"enum": 
			[
				"rebel",
				"imperial",
				"scum"
			],

			"description": "The faction this squadron belongs to."
		},

		"description": 
		{
			"type": "string",
			"description": "A description of this squadron."
		},

		"obstacles": 
		{
			"type": "array",
			"description": "Array of three Strings, each being an identifier for the obstacle chosen for tournament use.",
			"maxItems": 3,
			"minItems": 3,
			"items": 
			{
				"type": "string"
			}
		},

		"pilots": 
		{
			"type": "array",
			"description": "The members of this squadron.",
			"items": 
			{
				"type": "object",
				"minItems": 1,
				"required": 
				[
					"name",
					"ship"
				],

				"additionalProperties": false,
				"properties": 
				{
					"multisection_id": 
					{
						"type": "integer"
					},

					"points": 
					{
						"type": "integer",
						"description": "The total points spent creating this squadron."
					},

					"name": 
					{
						"type": "string",
						"pattern": "^[0-9a-z]+$"
					},

					"ship": 
					{
						"type": "string",
						"pattern": "^[0-9a-z]+$"
					},
					"hull": {
					    "type": "integer",
					    "description": "Hull value for the ship"
					},
					"shields": {
						"type": "integer",
						"description": "Shield value for the ship"
					},
					"upgrades": 
					{
						"type": "object",
						"additionalProperties": true,
						"minProperties": 1,
						"patternProperties": 
						{
							"^[0-9a-z]+$": 
							{
								"type": "array",
								"minItems": 1,
								"items": 
								{
									"type": "string",
									"pattern": "^[0-9a-z]+$"
								}
							}
						}
					},

					"vendor": 
					{
						"type": "object",
						"minProperties": 1,
						"maxProperties": 1,
						"description": "An extensible object containing app-specific data. Developers should put extra data here under their own namespace."
					}
				}
			}
		},

		"vendor": 
		{
			"type": "object",
			"minProperties": 1,
			"maxProperties": 1,
			"description": "An extensible object containing app-specific data. Developers should put extra data here under their own namespace."
		}
	}
}

=== NineWorlds/xstreamer/player2.json
{
    "version": "0.3.0",
    "name": "Palp Defenders",
    "faction": "imperial",
    "points": 100,
    "pilots": [
        {
            "name": "colonelvessery",
            "ship": "tiedefender",
            "points": 35,
            "upgrades": {
                "ept": [
                    "juke"
                ],
                "title": [
                    "tiex7"
                ]
            }
        },
        {
            "name": "countessryad",
            "ship": "tiedefender",
            "points": 36,
            "upgrades": {
                "ept": [
                    "pushthelimit"
                ],
                "title": [
                    "tiex7"
                ],
                "mod": [
                    "twinionenginemkii"
                ]
            }
        },
        {
            "name": "omicrongrouppilot",
            "ship": "lambdaclassshuttle",
            "points": 29,
            "upgrades": {
                "system": [
                    "collisiondetector"
                ],
                "crew": [
                    "emperorpalpatine"
                ]
            }
        }
    ],
    "vendor": {
        "voidstate": {
            "squadron_id": 597998,
            "link": "http://xwing-builder.co.uk/view/597998/palp-defenders",
            "builder": "Voidstate's Unofficial X-Wing Squadron Builder",
            "builder_link": "http://xwing-builder.co.uk/build"
        }
    }
}

=== NineWorlds/xstreamer/player1.json
{
    "version": "0.3.0",
    "name": "Goon Squad",
    "faction": "scum",
    "points": 100,
    "pilots": [
        {
            "name": "manaroo",
            "ship": "jumpmaster5000",
            "points": 35,
            "upgrades": {
                "ept": [
                    "attannimindlink"
                ],
                "crew": [
                    "gonk"
                ],
                "samd": [
                    "r5p8"
                ],
                "illicit": [
                    "feedbackarray"
                ]
            }
        },
        {
            "name": "fennrau",
            "ship": "protectoratestarfighter",
            "points": 32,
            "upgrades": {
                "ept": [
                    "attannimindlink"
                ],
                "title": [
                    "concorddawnprotector"
                ],
                "mod": [
                    "autothrusters"
                ]
            }
        },
        {
            "name": "palobgodalhi",
            "ship": "hwk290",
            "points": 33,
            "upgrades": {
                "ept": [
                    "attannimindlink"
                ],
                "turret": [
                    "twinlaserturret"
                ],
                "crew": [
                    "dengar"
                ],
                "title": [
                    "moldycrow"
                ]
            }
        }
    ],
    "vendor": {
        "voidstate": {
            "squadron_id": 597997,
            "link": "http://xwing-builder.co.uk/view/597997/goon-squad",
            "builder": "Voidstate's Unofficial X-Wing Squadron Builder",
            "builder_link": "http://xwing-builder.co.uk/build"
        }
    }
}
